services:
  mongo:
    image: mongo:6
    container_name: l4d2-database
    restart: unless-stopped
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
    logging:
      driver: "none"

  api:
    build: .
    container_name: l4d2-api
    restart: unless-stopped
    env_file: .env
    ports:
      - "8989:8989"
    volumes:
    - ./bin:/l4d2api/bin
    - ./certs:/l4d2api/certs
    - ./controllers:/l4d2api/controllers
    - ./logs:/l4d2api/logs
    - ./models:/l4d2api/models
    - ./public:/l4d2api/public
    - ./routes:/l4d2api/routes
    - ./uploads:/l4d2api/uploads
    - ./utils:/l4d2api/utils
    - ./views:/l4d2api/views
    depends_on:
      - mongo
    command: npm start

volumes:
  mongo-data: